name: Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: Vercel - aifactory-v0: aifactory